services:
  bodybalance:
    image: langowen/bodybalance
    container_name: bodybalance
    ports:
      - "8083:80"
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
        mode: "non-blocking"
        loki-retries: "5"
        loki-batch-wait: "10s"
        loki-pipeline-stages: |
          - regex:
              expression: '^\x1b\[(\d+)m(?P<level>[A-Z]{4})\x1b\[0m'
          - labels:
              level:
          - timestamp:
              source: time
              format: RFC3339Nano
    environment:
      - BD_USER=bodybalance
      - BD_PORT=5432
      - BD_HOST=postgres_body
      - BD_DBNAME=bodybalance
      - BD_PASSWORD=${BD_PASSWORD}
      - BD_SCHEMA=public
      - HTTP_PORT=80
      - HTTP_SIGNING_KEY=${SIGNING_KEY}
      - LOG_LEVEL=debug
     # - PATCH_CONFIG=./config/dev.yaml
      - BASE_URL=https://api.7375.org
      - VIDEO_PATCH=data/video
      - IMAGES_PATCH=data/img
      - TZ=Europe/Moscow
      - DOCS_USER=${DOCS_USER}
      - DOCS_PASSWORD=${DOCS_PASSWORD}
      - ENV=prod
    volumes:
      - /srv/docker/bodybalance/video/:/app/data/video/
      - /srv/docker/bodybalance/config/:/app/config/
      - /srv/docker/bodybalance/img/:/app/data/img/
    restart: unless-stopped
    depends_on:
      - postgres_body
    networks:
      body:

  postgres_body:
    image: postgres:16
    container_name: postgres_body
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
        mode: "non-blocking"
        loki-retries: "5"
        loki-batch-wait: "10s"
        loki-pipeline-stages: |
          - regex:
              expression: '^\x1b\[(\d+)m(?P<level>[A-Z]{4})\x1b\[0m'
          - labels:
              level:
          - timestamp:
              source: time
              format: RFC3339Nano
    environment:
      POSTGRES_DB: bodybalance
      POSTGRES_USER: bodybalance
      POSTGRES_PASSWORD: ${BD_PASSWORD}
    ports:
      - '5455:5432'
    volumes:
      - '/srv/docker/bodybalance/pg:/var/lib/postgresql/data'
    networks:
      body:

networks:
  body:
    driver: bridge