{
 "title": "BodyBalance Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "P1", "label": "Источник данных Prometheus", "query": "prometheus" },
   { "name": "L1", "label": "Источник данных Loki", "query": "loki" },
   {
    "name": "service",
    "label": "Выберите сервис",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Метрики приложения", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Запросы к Админ API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(bodybalance_admin_requests_total[5m])) by (endpoint)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Запросы к Mobile API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(bodybalance_api_requests_total[5m])) by (endpoint)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Топ-5 самых медленных эндпоинтов",
   "type": "bargauge",
   "description": "Топ-5 самых медленных эндпоинтов",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, histogram_quantile(0.95, sum by(endpoint, le) (rate(bodybalance_request_duration_seconds_bucket[10m]))))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Запросы за последние 5 минут",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(bodybalance_admin_requests_total[5m]))",
     "legendFormat": "Admin API"
    },
    {
     "expr": "sum(increase(bodybalance_api_requests_total[5m]))",
     "legendFormat": "Mobile API"
    }
   ]
  },
  {
   "title": "Анализ запросов по User-Agent (30 дней)",
   "type": "table",
   "description": "Статистика запросов по уникальным User-Agent за последние 30 дней",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(50, sum by(user_agent) (count_over_time({service_name=\"$service\"} | json | user_agent != \"\" [$__interval])))",
     "legendFormat": "{{user_agent}}"
    },
    {
     "expr": "sum by(user_agent) (count_over_time({service_name=\"$service\"} | json | user_agent != \"\" [$__range]))",
     "legendFormat": "{{user_agent}}"
    },
    {
     "expr": "sum by(user_agent) (count_over_time({service_name=\"$service\", user_agent=~\"chrome|firefox|safari|curl\"} | json [$__range]))",
     "legendFormat": "{{user_agent}}"
    }
   ]
  },
  {
   "title": "Топ-5 наиболее популярных файлов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5, sum(rate(bodybalance_static_file_requests_total[5m])) by (filename))",
     "legendFormat": "{{filename}}"
    }
   ]
  },
  {
   "title": "Топ-5 самых медленных для загрузки файлов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(5, avg by(filename) (bodybalance_static_file_load_time_seconds_bucket))",
     "legendFormat": "{{filename}}"
    }
   ]
  },
  {
   "title": "Количество ошибок (статус >= 400)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(bodybalance_admin_requests_total{status=~\"4.*|5.*\"}[5m]))",
     "legendFormat": "Admin API ошибки"
    },
    {
     "expr": "sum(rate(bodybalance_api_requests_total{status=~\"4.*|5.*\"}[5m]))",
     "legendFormat": "Mobile API ошибки"
    }
   ]
  },
  {
   "title": "Время обработки запросов (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(bodybalance_request_duration_seconds_bucket[5m])) by (handler, le))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Анализ статических файлов",
   "type": "table",
   "description": "Отображение размеров файлов и времени их загрузки",
   "gridPos": { "h": 16, "w": 6, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "avg by(filename) (bodybalance_static_file_size_bytes)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by(filename) (bodybalance_static_file_load_time_seconds)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(filename) (bodybalance_static_file_requests_total)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by(filename) (bodybalance_static_file_transfer_rate_bytes_per_second)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Среднее время загрузки файлов по типам",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(bodybalance_static_file_load_time_seconds_bucket{file_type=\"video\"})",
     "legendFormat": "Видео"
    },
    {
     "expr": "avg(bodybalance_static_file_load_time_seconds_bucket{file_type=\"image\"})",
     "legendFormat": "Изображения"
    }
   ]
  },
  {
   "title": "Пропускная способность сервера (статические файлы)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "sum(rate(bodybalance_static_file_transfer_rate_bytes_per_second_bucket[1m])) * 60 / 1024",
     "legendFormat": "Общий трафик"
    },
    {
     "expr": "sum(rate(bodybalance_static_file_transfer_rate_bytes_per_second_bucket{file_type=\"video\"}[1m])) * 60 / 1024",
     "legendFormat": "Видео"
    },
    {
     "expr": "sum(rate(bodybalance_static_file_transfer_rate_bytes_per_second_bucket{file_type=\"image\"}[1m])) * 60 / 1024",
     "legendFormat": "Изображения"
    }
   ]
  },
  {
   "title": "Эффективность кэширования контента",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bodybalance_static_file_cache_hits_total)",
     "legendFormat": "Кэшированные запросы"
    },
    {
     "expr": "sum(bodybalance_static_file_requests_total) - sum(bodybalance_static_file_cache_hits_total)",
     "legendFormat": "Полные загрузки"
    }
   ]
  },
  { "title": "Go Runtime метрики", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Версия Go",
   "type": "stat",
   "description": "Информация о текущей версии Go",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_info" }
   ]
  },
  {
   "title": "Профиль памяти",
   "type": "timeseries",
   "description": "Использование памяти кучей Go",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "go_memstats_heap_inuse_bytes", "legendFormat": "Байт в использовании кучи" },
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "Байт выделено" },
    { "expr": "go_memstats_stack_inuse_bytes", "legendFormat": "Байт стека горутин" }
   ]
  },
  {
   "title": "Нагрузка на CPU",
   "type": "timeseries",
   "description": "Использование процессора приложением в процентах",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "CPU использование"
    }
   ]
  },
  {
   "title": "Количество горутин",
   "type": "gauge",
   "description": "Количество активных горутин в приложении",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Время сборки мусора (GC)",
   "type": "timeseries",
   "description": "Время, затрачиваемое на сборку мусора (GC)",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{quantile=\"0.5\"}",
     "legendFormat": "GC Медиана (p50)"
    },
    {
     "expr": "go_gc_duration_seconds{quantile=\"0.75\"}",
     "legendFormat": "GC p75"
    },
    {
     "expr": "go_gc_duration_seconds{quantile=\"1\"}",
     "legendFormat": "GC Максимум (p100)"
    }
   ]
  },
  {
   "title": "Фрагментация памяти",
   "type": "gauge",
   "description": "Фрагментация памяти = (heap_inuse_bytes - alloc_bytes) / heap_inuse_bytes",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(go_memstats_heap_inuse_bytes - go_memstats_alloc_bytes) / go_memstats_heap_inuse_bytes",
     "legendFormat": "Фрагментация"
    }
   ]
  },
  {
   "title": "Частота GC (раз/сек)",
   "type": "timeseries",
   "description": "Частота запуска сборки мусора",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_count[1m])",
     "legendFormat": "GC/сек"
    }
   ]
  },
  {
   "title": "Количество OS потоков",
   "type": "timeseries",
   "description": "Общее количество потоков, создаваемых приложением",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 76 },
   "targets": [
    { "expr": "go_threads", "legendFormat": "OS потоки" }
   ]
  },
  {
   "title": "Файловые дескрипторы",
   "type": "gauge",
   "description": "Отношение открытых файловых дескрипторов к максимально возможному количеству",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds / process_max_fds",
     "legendFormat": "Использование файловых дескрипторов"
    }
   ]
  },
  { "title": "Логи приложения", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Анализ запросов по IP ",
   "type": "table",
   "description": "Статистика запросов по уникальным IP",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(50, sum by(remote_addr) (count_over_time({service_name=\"$service\"} | json | remote_addr != \"\" [$__interval])))",
     "legendFormat": "{{remote_addr}}"
    },
    {
     "direction": "backward",
     "expr": "sum by(remote_addr) (count_over_time({service_name=\"$service\"} | json | remote_addr != \"\" [$__range]))",
     "legendFormat": "{{remote_addr}}"
    },
    {
     "direction": "backward",
     "expr": "sum by(remote_addr) (count_over_time({service_name=\"$service\", remote_addr=~\"chrome|firefox|safari|curl\"} | json [$__range]))",
     "legendFormat": "{{remote_addr}}"
    }
   ]
  },
  {
   "title": "Анализ запросов по User-Agent",
   "type": "table",
   "description": "Статистика запросов по уникальным User-Agent за последние 30 дней",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(50, sum by(user_agent) (count_over_time({service_name=\"$service\"} | json | user_agent != \"\" [$__interval])))",
     "legendFormat": "{{user_agent}}"
    },
    {
     "direction": "backward",
     "expr": "sum by(user_agent) (count_over_time({service_name=\"$service\"} | json | user_agent != \"\" [$__range]))",
     "legendFormat": "{{user_agent}}"
    },
    {
     "direction": "backward",
     "expr": "sum by(user_agent) (count_over_time({service_name=\"$service\", user_agent=~\"chrome|firefox|safari|curl\"} | json [$__range]))",
     "legendFormat": "{{user_agent}}"
    }
   ]
  },
  {
   "title": "Logs Volume",
   "type": "timeseries",
   "description": "Визуализация объема логов по времени с разбивкой по уровням",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(level) (count_over_time({service_name=~\"$service\"} | json | label_format level=detected_level | user_agent != `Prometheus/3.4.1` [$__interval]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Логи приложения",
   "type": "logs",
   "description": "Просмотр логов приложения",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 101 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\"$service\"} | json | label_format level=detected_level | user_agent != `Prometheus/3.4.1`",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "Количество логов по уровням и сервисам",
   "type": "timeseries",
   "description": "Количество логов по уровням (error, warn, info, debug) и сервисам",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 113 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(service_name, level) (count_over_time({service_name=\"$service\"} | json | label_format level=detected_level | level = `error` | user_agent != `Prometheus/3.4.1` [1m]))",
     "legendFormat": "{{service_name}}|{{level}}"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name, level) (count_over_time({service_name=\"$service\"} | json | label_format level=detected_level | level = `warn` | user_agent != `Prometheus/3.4.1` [1m]))",
     "legendFormat": "{{service_name}}|{{level}}"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name, level) (count_over_time({service_name=\"$service\"} | json | label_format level=detected_level | level = `info` | user_agent != `Prometheus/3.4.1` [1m]))",
     "legendFormat": "{{service_name}}|{{level}}"
    },
    {
     "direction": "backward",
     "expr": "sum by(service_name, level) (count_over_time({service_name=\"$service\"} | json | label_format level=detected_level | level = `debug` | user_agent != `Prometheus/3.4.1` [1m]))",
     "legendFormat": "{{service_name}}|{{level}}"
    }
   ]
  },
  {
   "title": "Топ ошибок за 24 часа",
   "type": "table",
   "description": "Топ ошибок в приложении ",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 113 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{service_name=\"$service\"} | label_format level=detected_level | level != `info`",
     "legendFormat": "{{error}}"
    }
   ]
  }
 ]
}