global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'bodybalance'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['bodybalance:80']
        labels:
          service: 'bodybalance'
          environment: 'production'

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
