basePath: /api/v1
host: https://body.7375.org
info:
  contact:
    email: info@7375.org
    name: Sergei
  description: API для управления видео-контентом BodyBalance.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: BodyBalance API
  version: "1.0"
paths: {}
swagger: "2.0"
